{"timestamp":"2025-08-26T23:35:11.187789","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-26T23:35:11.196265","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/elasticsearch_hook.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-26T23:35:11.509888","level":"warning","event":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py:471: DeprecationWarning: Using Connection.get_connection_from_secrets from `airflow.models` is deprecated.Please use `from airflow.sdk import Connection` instead\n  warnings.warn(\n","logger":"py.warnings"}
{"timestamp":"2025-08-26T23:35:11.547350","level":"info","event":"Connection Retrieved 'elasticsearch_default'","logger":"airflow.hooks.base"}
{"timestamp":"2025-08-26T23:35:15.608945","level":"info","event":"GET http://elastic:9200/ [status:N/A duration:4.040s]","logger":"elastic_transport.transport"}
{"timestamp":"2025-08-26T23:35:15.609162","level":"warning","event":"Node <Urllib3HttpNode(http://elastic:9200)> has failed for 1 times in a row, putting on 1 second timeout","logger":"elastic_transport.node_pool"}
{"timestamp":"2025-08-26T23:35:15.609230","level":"warning","event":"Retrying request after failure (attempt 0 of 3)","logger":"elastic_transport.transport","error_detail":[{"exc_type":"ConnectionError","exc_value":"Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7013ce9c0440>: Failed to resolve 'elastic' ([Errno -5] No address associated with hostname))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_transport.py","lineno":342,"name":"perform_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py","lineno":202,"name":"perform_request"}],"is_group":false,"exceptions":[]},{"exc_type":"NameResolutionError","exc_value":"<urllib3.connection.HTTPConnection object at 0x7013ce9c0440>: Failed to resolve 'elastic' ([Errno -5] No address associated with hostname)","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py","lineno":167,"name":"perform_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":449,"name":"increment"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py","lineno":39,"name":"reraise"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":493,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":494,"name":"request"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1333,"name":"endheaders"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1093,"name":"_send_output"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1037,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":325,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":205,"name":"_new_conn"}],"is_group":false,"exceptions":[]},{"exc_type":"gaierror","exc_value":"[Errno -5] No address associated with hostname","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":198,"name":"_new_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py","lineno":60,"name":"create_connection"},{"filename":"/usr/local/lib/python3.12/socket.py","lineno":978,"name":"getaddrinfo"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-26T23:35:19.622251","level":"info","event":"GET http://elastic:9200/ [status:N/A duration:4.006s]","logger":"elastic_transport.transport"}
{"timestamp":"2025-08-26T23:35:19.622525","level":"warning","event":"Node <Urllib3HttpNode(http://elastic:9200)> has failed for 2 times in a row, putting on 2 second timeout","logger":"elastic_transport.node_pool"}
{"timestamp":"2025-08-26T23:35:19.622645","level":"warning","event":"Retrying request after failure (attempt 1 of 3)","logger":"elastic_transport.transport","error_detail":[{"exc_type":"ConnectionError","exc_value":"Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7013ce9c0620>: Failed to resolve 'elastic' ([Errno -5] No address associated with hostname))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_transport.py","lineno":342,"name":"perform_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py","lineno":202,"name":"perform_request"}],"is_group":false,"exceptions":[]},{"exc_type":"NameResolutionError","exc_value":"<urllib3.connection.HTTPConnection object at 0x7013ce9c0620>: Failed to resolve 'elastic' ([Errno -5] No address associated with hostname)","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py","lineno":167,"name":"perform_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":449,"name":"increment"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py","lineno":39,"name":"reraise"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":493,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":494,"name":"request"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1333,"name":"endheaders"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1093,"name":"_send_output"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1037,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":325,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":205,"name":"_new_conn"}],"is_group":false,"exceptions":[]},{"exc_type":"gaierror","exc_value":"[Errno -5] No address associated with hostname","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":198,"name":"_new_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py","lineno":60,"name":"create_connection"},{"filename":"/usr/local/lib/python3.12/socket.py","lineno":978,"name":"getaddrinfo"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-26T23:35:19.623515","level":"info","event":"Resurrected node <Urllib3HttpNode(http://elastic:9200)> (force=False)","logger":"elastic_transport.node_pool"}
{"timestamp":"2025-08-26T23:35:23.628746","level":"info","event":"GET http://elastic:9200/ [status:N/A duration:4.005s]","logger":"elastic_transport.transport"}
{"timestamp":"2025-08-26T23:35:23.629365","level":"warning","event":"Node <Urllib3HttpNode(http://elastic:9200)> has failed for 3 times in a row, putting on 4 second timeout","logger":"elastic_transport.node_pool"}
{"timestamp":"2025-08-26T23:35:23.629740","level":"warning","event":"Retrying request after failure (attempt 2 of 3)","logger":"elastic_transport.transport","error_detail":[{"exc_type":"ConnectionError","exc_value":"Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7013ce9c0ce0>: Failed to resolve 'elastic' ([Errno -5] No address associated with hostname))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_transport.py","lineno":342,"name":"perform_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py","lineno":202,"name":"perform_request"}],"is_group":false,"exceptions":[]},{"exc_type":"NameResolutionError","exc_value":"<urllib3.connection.HTTPConnection object at 0x7013ce9c0ce0>: Failed to resolve 'elastic' ([Errno -5] No address associated with hostname)","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py","lineno":167,"name":"perform_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":449,"name":"increment"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py","lineno":39,"name":"reraise"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":493,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":494,"name":"request"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1333,"name":"endheaders"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1093,"name":"_send_output"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1037,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":325,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":205,"name":"_new_conn"}],"is_group":false,"exceptions":[]},{"exc_type":"gaierror","exc_value":"[Errno -5] No address associated with hostname","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":198,"name":"_new_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py","lineno":60,"name":"create_connection"},{"filename":"/usr/local/lib/python3.12/socket.py","lineno":978,"name":"getaddrinfo"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-26T23:35:23.631143","level":"info","event":"Resurrected node <Urllib3HttpNode(http://elastic:9200)> (force=False)","logger":"elastic_transport.node_pool"}
{"timestamp":"2025-08-26T23:35:27.634526","level":"info","event":"GET http://elastic:9200/ [status:N/A duration:4.003s]","logger":"elastic_transport.transport"}
{"timestamp":"2025-08-26T23:35:27.634687","level":"warning","event":"Node <Urllib3HttpNode(http://elastic:9200)> has failed for 4 times in a row, putting on 8 second timeout","logger":"elastic_transport.node_pool"}
{"timestamp":"2025-08-26T23:35:27.635345","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"ConnectionError","exc_value":"Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7013ce9c0440>: Failed to resolve 'elastic' ([Errno -5] No address associated with hostname)))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":890,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1177,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/elasticsearch_hook.py","lineno":16,"name":"do_some_stuff"},{"filename":"/opt/airflow/plugins/elasticsearch_plugin/hooks/elasticsearch_hook.py","lineno":47,"name":"info"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elasticsearch/_sync/client/utils.py","lineno":452,"name":"wrapped"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elasticsearch/_sync/client/__init__.py","lineno":3065,"name":"info"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elasticsearch/_sync/client/_base.py","lineno":271,"name":"perform_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elasticsearch/_sync/client/_base.py","lineno":315,"name":"_perform_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_transport.py","lineno":342,"name":"perform_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py","lineno":202,"name":"perform_request"}],"is_group":false,"exceptions":[]},{"exc_type":"NameResolutionError","exc_value":"<urllib3.connection.HTTPConnection object at 0x7013ce9c1070>: Failed to resolve 'elastic' ([Errno -5] No address associated with hostname)","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py","lineno":167,"name":"perform_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":449,"name":"increment"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py","lineno":39,"name":"reraise"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":493,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":494,"name":"request"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1333,"name":"endheaders"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1093,"name":"_send_output"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1037,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":325,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":205,"name":"_new_conn"}],"is_group":false,"exceptions":[]},{"exc_type":"gaierror","exc_value":"[Errno -5] No address associated with hostname","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":198,"name":"_new_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py","lineno":60,"name":"create_connection"},{"filename":"/usr/local/lib/python3.12/socket.py","lineno":978,"name":"getaddrinfo"}],"is_group":false,"exceptions":[]}]}
